### ISSUE TITLE
create_component fails with subtasks

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#109]
`create_component` needs to be somehow aware of subtask structure. Currently fails.

```shell
viash run src/common/create_component/config.vsh.yaml -- \
  --task batch_integration \
  --type method \
  --name my_new_method
```

```
[error] Input file 'src/batch_integration/api/comp_method.yaml' does not exist.
Files and logs are stored at '/tmp/viash_create_component3018914635213393711'
```

**Comment by rcannood** [comment]
Indeed. Right now, to create a new component for the `batch_integration` task, you'd need to use the following code:

```bash
viash run src/common/create_component/config.vsh.yaml -- \
  --task batch_integration \
  --type method \
  --name my_new_method \
  --api_file src/batch_integration/api/comp_method_feature.yaml
```

---

At the very least, the error message should be a bit more helpful. For example:

```bash
viash run src/common/create_component/config.vsh.yaml -- \
  --task batch_integration \
  --type method \
  --name my_new_method
```

    Error: The 'batch_integration' task has multiple method subtypes. Detected subtypes are 'embed', 'feature', 'graph'.
    Please manually specify the --api_file parameter. Example: 
      --api_file src/batch_integration/api/comp_method_embed.yaml

---

A better solution would be to add a secondary parameter `--subtype`.


```bash
viash run src/common/create_component/config.vsh.yaml -- \
  --task batch_integration \
  --type method \
  --name my_new_method
```

    Error: The 'batch_integration' task requires a value for --subtype (e.g. 'embed', 'feature', or 'graph').

---

WDYT? :)

**Comment by rcannood** [comment]
#161 changes the error message you get when running the example command:

```bash
viash run src/common/create_component/config.vsh.yaml --   --task batch_integration   --type method   --name my_new_method
```

    Could not find component API file at location 'src/tasks/batch_integration/api/comp_method.yaml'.
    You might need to manually specify a value for the '--api_file' parameter.
    
    Detected component API files:
    - src/tasks/batch_integration/api/comp_method_embedding.yaml
    - src/tasks/batch_integration/api/comp_method_feature.yaml
    - src/tasks/batch_integration/api/comp_method_graph.yaml
    - src/tasks/batch_integration/api/comp_metric_embedding.yaml
    - src/tasks/batch_integration/api/comp_metric_feature.yaml
    - src/tasks/batch_integration/api/comp_metric_graph.yaml
    - src/tasks/batch_integration/api/comp_process_dataset.yaml

**Comment by scottgigante-immunai** [comment]
Can we add something in the docs about this too? Last time I looked the create component docs didn't mention `--api_file` at all.

**Comment by rcannood** [comment]
Update: I changed the component again.

```bash
viash run src/common/create_component/config.vsh.yaml --\
  --task batch_integration \
  --type method \
  --name my_new_method
```

    Error: Invalid --type argument.
      Reason: Could not find API file at 'src/tasks/batch_integration/api/comp_method.yaml'.
      Possible values for --type: method_embedding, method_feature, method_graph, metric_embedding, metric_feature, metric_graph, process_dataset.

----

I'll add something to the docs about this matter :)

**Comment by scottgigante-immunai** [comment]
Great! This is a huge improvement, thank you
