### ISSUE TITLE
Use shared docker containers for methods with identical dependencies

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#111]
Currently, all python-based methods require `pyyaml` and `anndata`. Installing these creates a docker image per method which adds a tonne of both runtime and disk storage overhead which could be shared.

I'd propose we provide a range of standard base images (as we do in v1) for common dependencies, starting with a python 3.10 + pyyaml + anndata image.

**Comment by rcannood** [comment]
Agreed! :+1:

**Comment by rcannood** [comment]
Alternatively, we can just have a smaller set of base images with our 'recommended' version of R and Python. For example:

* ghcr.io/openproblems-bio/base-image-python:<tag?>
  - Has Python 3.10
  - anndata~=0.8.0
  - pyyaml
* ghcr.io/openproblems-bio/base-image-r:<tag?>
  - Uses r2u
  - Has Python 3.10
  - anndata~=0.8.0
  - pyyaml
  - anndata for R
* ghcr.io/openproblems-bio/base-image-bioc:<tag?>
  - same as `base-image-r` but with some Bioconductor

**Comment by scottgigante-immunai** [comment]
Let's start with the smaller set, and add on as we see fit based on what individual images are using.

**Comment by rcannood** [comment]
This github issue was accidentally closed when https://github.com/openproblems-bio/base-images/pull/1 was merged. Reopening as these images aren't available for use just yet.
