### ISSUE TITLE
Change `anndata~=0.8` to `anndata~=0.8.0`

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#114]
`anndata~=0.8` is equivalent to `anndata>=0.8,==0.*`. Given 0.8 introduced many breaking changes, I would expect the same for 0.9.

**Comment by rcannood** [comment]
Good point. This only seems to affect the `create_component` component, but I updated all other components to use `anndata~=0.8.0` instead of `anndata>=0.8`.
