### ISSUE TITLE
Rename `par` -> `params`

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#115]
I'm a big fan of readable code, and `par` doesn't obviously mean anything

**Comment by rcannood** [comment]
This is better suited as a suggestion for [viash-io/viash issue tracker](https://github.com/viash-io/viash/issues).

Changing the interface from `par` to `params` would be a major breaking issue, but something we could consider for the Viash 1.0 or later releases.
