### ISSUE TITLE
Dryrun for pipeline

### ISSUE THREAD

**Issue by mumichae** [openproblems-bio/openproblems-v2#14]
Add the nextflow stub feature for pieplien dry runs

- [x] update viash
- [ ] add to documents

**Comment by rcannood** [comment]
It should work using Viash >0.6.1 (I think) by adding `-stub` to your command. Example:

```bash
bin/nextflow \
  run . \
  -main-script src/label_projection/workflows/run/main.nf \
  -profile docker \
  -params-file "$params_file" \
  --publish_dir "$OUTPUT_DIR" \
  -stub

**Comment by rcannood** [comment]
Viash 0.6.4 simplifies this quite a bit, as the pipeline doesn't require valid parameters to be passed:

```bash
nextflow run src/label_projection/workflows/run/main.nf -stub
```
