### ISSUE TITLE
Existing task READMEs do not follow proposed structure

### ISSUE THREAD

**Issue by scottgigante-immunai** [openproblems-bio/openproblems-v2#169]
Doesn't look like any existing tasks follow the proposed README structure in https://openproblems.bio/documentation/create_task/define_task.html#create-a-readme. It would be helpful to at least have one README that follows the best practices to link to in the docs as an example of best practices.

**Comment by KaiWaldrant** [comment]
This has changed to an issue
see #180

**Comment by scottgigante-immunai** [comment]
So there's nothing in the repo describing the task motivation or description except in a closed issue? How are we going to generate the website content from the v2 repo?
