### ISSUE TITLE
More slots in processed datasets?

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/openproblems-v2#17]
At the moment a 'common' dataset has the following format ([`src/datasets/api/anndata_dataset.yaml`](https://github.com/openproblems-bio/openproblems-v2/blob/183eeb8c4d893fd6a14b24bda3f9e70ea2681687/src/datasets/api/anndata_dataset.yaml)):

```
AnnData object with n_obs × n_vars = 16382 × 18771
    obs: 'celltype', 'batch', tissue'
    uns: 'dataset_id'
    layers: 'counts', 'log_cpm', 'log_scran_pooling', 'sqrt_cpm'
```

The `log_cpm`, `log_scran_pooling` and `sqrt_cpm` layers were added because a lot of methods use one of these three normalisation techniques as the default. 

However, I'm noticing a lot also use a PCA dimensionality reduction or the set of HVG genes. We could add those slots to be part of the spec as well, so that a common dataset looks as follows:

```
AnnData object with n_obs × n_vars = 16382 × 18771
    obs: 'celltype', 'batch', tissue'
    var: 'hvg_log_cpm', 'hvg_log_scran_pooling', 'hvg_sqrt_cpm'
    uns: 'dataset_id'
    obsm: 'log_cpm_pca', 'log_scran_pooling_pca', 'sqrt_cpm_pca'
    layers: 'counts', 'log_cpm', 'log_scran_pooling', 'sqrt_cpm'
```

Thoughts?

**Comment by scottgigante** [comment]
Is it wise to store all of this in the same object? For large datasets,
we're effectively making the dataset resource usage (both memory and
network) ~5x bigger (4 layers, 3 hvg layers) when most methods will only
use one of these. Could we instead have the component compute all of these
and save them as different outputs which methods can then choose from?

**Comment by rcannood** [comment]
Hmm.. I made the switch from `layers: {'counts': ..., 'normalized': ...}` to this variant because it's more practical in that a method can at runtime decide which normalisation method to use or choose its own; my thinking was that if it becomes too big to load into memory we can always use the on-disk format.

But you're absolutely right, transfer costs also play an important role in this equation, and there's no way around it with AnnData as a data format.

I'll make the necessary changes tomorrow to drop the various layers in favour for one normalized layer per h5ad file. Doing so resolves the original problem in this issue ^^

> 3 hvg layers
I wasn't intending on making a separate hvg matrix but rather store a boolean in .var so the AnnData can be subset when needed.
