### ISSUE TITLE
Create match modalities process_dataset component

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/openproblems-v2#238]
There's an API file at `src/tasks/match_modalities/api/comp_process_dataset.yaml`, but no component that actually implements it

- [x] Create a `process_dataset` component which subsets the multimodal datasets (e.g. `resources_test/common/scicar_cell_lines/`) into what the methods and metrics of this task expect

**Comment by KaiWaldrant** [comment]
closed in #259
