### ISSUE TITLE
Change LICENSE

### ISSUE THREAD

**Issue by rcannood** [openproblems-bio/openproblems-v2#3]
Shall I change the LICENSE from GPL3 to MIT?

@LuckyMD @dburkhardt @LouiseDck Can you confirm this is OK?

**Comment by LouiseDck** [comment]
Sounds great to me, I generally prefer a more permissive license.

**Comment by LuckyMD** [comment]
I have no strong opinions here... more permissible is better in general I would say. But I vaguely recall this was something CZ Biohub or @olgabot specifically had some thoughts on.

**Comment by rcannood** [comment]
@dburkhardt Is this okay for you too?

**Comment by rcannood** [comment]
Solved
