### ISSUE TITLE
CONTRIBUTING.md instructions not working

### ISSUE THREAD

**Issue by Martin-Fahrenberger** [openproblems-bio/openproblems-v2#41]
Hi openproblems-v2 Team,

When following along the quickstart instructions in CONTRIBUTING.md

`bin/viash_build -q 'label_projection|common'`

is no longer working.
On first sight it looks like `viash_build` is now called via `viash build` but then also the -q option doesnt work anymore, so it might not be that easy.

Thanks for taking a look

**Comment by rcannood** [comment]
Hi @Martin-Fahrenberger ! Thanks for bringing this up. I just merged an update to the contributing papge. Is this working for you now?

**Comment by rcannood** [comment]
Hi Martin! 

Just checking in to see if you managed to get everything to work.

Kind regards,
Robrecht

**Comment by Martin-Fahrenberger** [comment]
Hi Robrecht,

Thanks for taking care of this, I got one step further now.

The next issue seems to be that the generated run_test.sh wants to start nextflow from `bin/nextflow`.
But the nextflow install instructions install it in a different location `$HOME/bin/nextflow`, easy enough to fix though :)

Nextflow seems to be running the pipeline now 👍 

Martin
