### ISSUE TITLE
NeuralEE error when there are some zero-counts observations

### ISSUE THREAD

**Issue by jacorvar** [openproblems-bio/openproblems-v2#45]
The `neuralee` method at dimensionality reduction fails with (big) datasets such as _cengen_ when filtering high variable genes. The function in charge of it, namely `subsample_genes` does not only filter out low variable genes, but also observations (cells) with zero counts after removing low variable genes. This reduces the number of observations, which differs from the original dataset. 

In the case of _mouse_blood_olssen_labeled_ dataset, the number of obs is downsized from 600 to 445. Since the `N_small` argument of the `affinity_split` function takes the minimum value between 1000 and the size of the original dataset, it will be 600, which is larger than the current (downsampled) dataset and hence throws an error.
```
Load input data
Add method and normalization ID
Select top 500 high variable genes
Downsampling from 116918 to 500 genes
Cells with zero expression in all genes considered were removed
Downsampling from 660 to 445 cells
Compute affinity, perplexity=30.0, N_small=660, on each batch
Traceback (most recent call last):
  File "/home/rcannood/workspace/openproblems/openproblems-v2/work/d8/5bbc404aa5fa6942b38763c49e7466/.viash_script.sh", line 60, in <module>
    dataset.affinity_split(N_small=min(1000, input.n_obs))
  File "/usr/local/lib/python3.10/site-packages/neuralee/dataset/dataset.py", line 103, in affinity_split
    self.Y_splits = self.Y[indexes].reshape(split, N_small, -1)
ValueError: cannot reshape array of size 0 into shape (0,660,newaxis)
```
In the case of _cengen_ dataset, you end up with an `X_emb` matrix with 3 less obs than the original dataset, and that's why the error.
```
Load input data
Add method and normalization ID
Select top 500 high variable genes
Downsampling from 22469 to 500 genes
Cells with zero expression in all genes considered were removed
Downsampling from 100955 to 100952 cells
Compute affinity, perplexity=30.0, N_small=1000, on each batch
Neural Elastic Embedding, lambda=1, completed in 654.13s.
Traceback (most recent call last):
  File "/home/rcannood/workspace/openproblems/openproblems-v2/work/10/31302e880af22e7aa4673f30b95fab/.viash_script.sh", line 67, in <module>
    input.obsm["X_emb"] = res["X"].detach().cpu().numpy()
  File "/usr/local/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 151, in __setitem__
    value = self._validate_value(value, key)
  File "/usr/local/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 215, in _validate_value
    return super()._validate_value(val, key)
  File "/usr/local/lib/python3.10/site-packages/anndata/_core/aligned_mapping.py", line 52, in _validate_value
    raise ValueError(
ValueError: Value passed for key 'X_emb' is of incorrect shape. Values of obsm must match dimensions (0,) of parent. Value had shape (100952, 2) while it should have had (100955,).
```

The root of the problem stems from the [`update_genes`]((https://neuralee.readthedocs.io/en/latest/_modules/neuralee/dataset/dataset.html#GeneExpressionDataset.update_genes)) function, which is called by `subsample_genes` and which removes the zero counts cells.

To solve the issue we'd have to modify the NeuralEE package. One option would be to choose whether to keep the zero-count cells. This issue also occurs at v1.

**Comment by rcannood** [comment]
Seems to be fixed
