### ISSUE TITLE
running out of memory in `RMSE`

### ISSUE THREAD

**Issue by jacorvar** [openproblems-bio/openproblems-v2#46]
I run out of memory when running `rmse` method from dimensionality reduction task on my laptop (16Gb memory + 6Gb Swap) with the cengen dataset.

After having created a (full) dimensionally reduced embedding with all observations (100955), it ends up requiring several dozens of Gb. More specifically, the function `scipy.spatial.distance.pdist` function complains about not having enough space to allocate 38 Gb. 

Would there be any workarounds to run this task on my local computer or is it just a lack of enough memory?

**Comment by rcannood** [comment]
I see, so the component computes the pairwise distances between samples in the dimensionality reduction.

## Approach 1
I think the only scalable solution would be to subsample the cells for which to compute the pairwise distances. For instances, if a strategy I often used in cases like this is to only compute pairwise distances between 1000 cells and all remaining cells. In this way, you don't need to allocate a 100955 × 100955 matrix but instead a 1000 × 100995 matrix.

The question the becomes: which 1000 cells to select? There are various strategies for this, but I think it might be worthwhile to find out whether a 1000 (or even 5000, for that matter) would yield almost the same RMSE values (on average).

I wouldn't focus too much on this issue at the moment and instead go for another optimization:

## Approach 2

Looking at the code, it seems Scott swapped out the original RMSE code with `nnls()` to make the RMSE metric scale invariant: https://github.com/openproblems-bio/openproblems/pull/743/commits/79a38ef6c7162179b2ce66ccd93321fc4a817016

However, if we were computing a regular RMSE would could just iterate over the pairwise distance matrices without precomputing the pairwise distances beforehand.
