### ISSUE TITLE
high execution times of `rmse` method and `trustworthiness` and `density` metrics at dimensionality reduction

### ISSUE THREAD

**Issue by jacorvar** [openproblems-bio/openproblems-v2#48]
`rmse` method and `trustworthiness` and `density` metrics require a long execution time and a lot of memory to be executed.

Possible common cause might be the fact that the three processes calculate under the hood the pairwise (euclidean) distances for the full count matrix (stored in `.layers['counts']`). 

Would it make sense to create a novel component which precomputes the pairwise distances?
Related to #46

**Comment by rcannood** [comment]
closing this for now, will re-evaluate when necessary
